### PR TITLE
fix(#174): Fixes simulate and capture mode checker logic

### PR DESCRIPTION
**Pull request by lordofthejars**

### CODE REVIEW

**Comment by tommysitu** [comment]
Hi @lordofthejars, I'd recommend you to re-fork hoverfly-java project. It has been slimmed down to 2MB for easy cloning.

**Comment by lordofthejars** [comment]
ok, I will do but can you merge this PR? Or this is a blocker? I mention this because I'd need this fix ASAP :)

**Comment by tommysitu** [comment]
I deliberately changed the way it looks for test resource files using classloader instead of hardcoded relative path. But this PR will revert it back. I think the problem is that previously recorded file is by default stored under the `hoverfly` folder, and I forgot to append it in when I did the change. 

We can keep my change and fix your problem by appending `hoverfly/` to the `recordFile` input

**Comment by tommysitu** [comment]
I can fix it quickly

**Comment by tommysitu** [comment]
I will release this patch now, as it could cause problems with existing users

**Comment by lordofthejars** [comment]
No worries, I can wait until Monday :)

**Comment by tommysitu** [comment]
@lordofthejars I think your PR was a better fix, but it's not easy to rebase it on the latest master. I will redo what you did to fix issue #200

**Pull request closed without merging**
