### PR TITLE
Spy mode

### PR DESCRIPTION
**Pull request by 3sunnysideup**
to support the new spy mode: https://github.com/SpectoLabs/hoverfly/pull/680

the binaries is removed from scm, please use the gradle task to update hoverfly binaries

### CODE REVIEW

**Comment by tommysitu** [comment]
Hi @3sunnysideup, I have just rebased your branch on master, which contains the latest v0.15.0 hoverfly binaries. Do you need to make any more changes on this PR?

**Comment by 3sunnysideup** [comment]
no, thanks.

**Comment by tommysitu** [comment]
Looks good to me.

**Comment by pvorb** [comment]
Great addition. I would really like to use it in my project.

@tommysitu Is there a plan for a new release of hoverfly-java?

**Comment by tommysitu** [comment]
Thank you for your interest! Yes, a new release was planned this week. I'll ping you when it is available on Maven Central.

**Comment by tommysitu** [comment]
@pvorb version `0.9.3` is what you need. Happy Hoverflying!

**Comment by pvorb** [comment]
Awesome. Thanks a lot.

**Pull request closed without merging**
